# Generated by Django 3.2.9 on 2021-11-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('rating', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
