# Generated by Django 3.2.9 on 2021-11-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='img',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
